"""Public API for Sigil's governed external financial-data providers."""

from .models import (
    MAX_RESPONSE_BYTES,
    MAX_TIMEOUT_SECONDS,
    PROVIDER_SCHEMA_VERSION,
    FinancialDataAuthenticationError,
    FinancialDataCacheEntry,
    FinancialDataProviderError,
    FinancialDataProviderHealth,
    FinancialDataProviderMetadata,
    FinancialDataProvenance,
    FinancialDataRateLimitError,
    FinancialDataRequest,
    FinancialDataResponse,
    FinancialDataTransportError,
    FinancialDataValidationError,
    freeze_json,
    thaw_json,
)
from .registry import FinancialDataProvider, FinancialDataProviderRegistry
from .sec_edgar import (
    SEC_ADAPTER_VERSION,
    SEC_ALLOWED_HOSTS,
    SEC_PROVIDER_ID,
    SEC_SUPPORTED_OPERATIONS,
    SEC_USER_AGENT_ENVIRONMENT_VARIABLE,
    SECEdgarProvider,
    normalize_cik,
    sec_request,
)
from .transport import (
    BoundedMemoryCache,
    BoundedRateLimiter,
    CredentialPlacement,
    CredentialResolver,
    EnvironmentCredentialResolver,
    GovernedHTTPSTransport,
    MappingCredentialResolver,
    redact_text,
)

__all__ = [
    "MAX_RESPONSE_BYTES",
    "MAX_TIMEOUT_SECONDS",
    "PROVIDER_SCHEMA_VERSION",
    "SEC_ADAPTER_VERSION",
    "SEC_ALLOWED_HOSTS",
    "SEC_PROVIDER_ID",
    "SEC_SUPPORTED_OPERATIONS",
    "SEC_USER_AGENT_ENVIRONMENT_VARIABLE",
    "BoundedMemoryCache",
    "BoundedRateLimiter",
    "CredentialPlacement",
    "CredentialResolver",
    "EnvironmentCredentialResolver",
    "FinancialDataAuthenticationError",
    "FinancialDataCacheEntry",
    "FinancialDataProvider",
    "FinancialDataProviderError",
    "FinancialDataProviderHealth",
    "FinancialDataProviderMetadata",
    "FinancialDataProviderRegistry",
    "FinancialDataProvenance",
    "FinancialDataRateLimitError",
    "FinancialDataRequest",
    "FinancialDataResponse",
    "FinancialDataTransportError",
    "FinancialDataValidationError",
    "GovernedHTTPSTransport",
    "MappingCredentialResolver",
    "SECEdgarProvider",
    "freeze_json",
    "normalize_cik",
    "redact_text",
    "sec_request",
    "thaw_json",
]
