"""Deterministic Markdown generation for every output document.

Every function here builds Markdown by plain string composition from
already-validated, already-redacted Python data (:class:`EvidenceFact`,
:class:`Contradiction`, ...) -- there is no template-file loading and no
Jinja2 (or any other) template-expression evaluation of collector or vault
content, so there is no path by which vault text or collector output could
be interpreted as a template directive. Optional model-generated prose is
accepted only as an already-sanitized plain string (see
:mod:`hermes_docs_worker.ollama_client`) and is inserted into one bounded
paragraph, never into a heading, table, or link.

Every generated document ends with a provenance footer
(:mod:`hermes_docs_worker.provenance`) and passes through
:func:`hermes_docs_worker.redaction.redact_text` as a final defensive pass
before being returned.
"""

from __future__ import annotations

from typing import Optional, Sequence

from hermes_docs_worker.contradiction import Contradiction, VaultContradiction
from hermes_docs_worker.evidence import EvidenceFact, EvidenceSnapshot
from hermes_docs_worker.provenance import (
    provenance_entries_from_facts,
    render_provenance_footer,
)
from hermes_docs_worker.redaction import redact_text
from hermes_docs_worker.status import StatusValue

STATUS_LEGEND = (
    "Statements below are tagged with one of: **Implemented**, **Configured**, "
    "**Verified**, **Deployed**, **Unknown**, **Degraded**, **Blocked**, **Planned**. "
    "Only **Verified** and **Deployed** are based on a live, currently-observed "
    "signal — source code, templates, or tests are never sufficient to claim either."
)

_STATUS_EMOJI = {
    StatusValue.DEPLOYED: "🟢",
    StatusValue.VERIFIED: "🟢",
    StatusValue.CONFIGURED: "🟡",
    StatusValue.IMPLEMENTED: "🟡",
    StatusValue.PLANNED: "⚪",
    StatusValue.UNKNOWN: "⚪",
    StatusValue.DEGRADED: "🟠",
    StatusValue.BLOCKED: "🔴",
}


def _iso(epoch: int) -> str:
    import time

    return time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime(epoch))


def _finalize(document: str, facts: Sequence[EvidenceFact], generated_at_iso: str) -> str:
    footer = render_provenance_footer(
        provenance_entries_from_facts(facts), generated_at_iso=generated_at_iso
    )
    return redact_text(document.rstrip() + "\n" + footer)


def _status_table(facts: Sequence[EvidenceFact]) -> str:
    lines = ["| Status | Category | Label | Detail | Source | Collected |", "| --- | --- | --- | --- | --- | --- |"]
    for fact in sorted(facts, key=lambda f: (f.category, f.label)):
        emoji = _STATUS_EMOJI.get(fact.status, "⚪")
        detail = fact.detail.replace("|", "\\|") or "—"
        lines.append(
            f"| {emoji} {fact.status.value} | {fact.category} | {fact.label} | {detail} "
            f"| `{fact.source}` | {_iso(fact.collected_at)} |"
        )
    return "\n".join(lines)


def render_fleet_status(
    facts: Sequence[EvidenceFact], *, generated_at: int
) -> str:
    """``01-Dashboards/FLEET-STATUS.md`` -- current status of every observed
    fleet subject, most conservative status per subject."""
    generated_at_iso = _iso(generated_at)
    doc = [
        "# Fleet Status",
        "",
        f"_Generated by the Titan documentation worker at {generated_at_iso}._",
        "",
        STATUS_LEGEND,
        "",
        "## Observed subjects",
        "",
        _status_table(facts) if facts else "_No evidence collected this run._",
    ]
    return _finalize("\n".join(doc), facts, generated_at_iso)


def render_operations_dashboard(
    facts: Sequence[EvidenceFact],
    contradictions: Sequence[Contradiction],
    *,
    generated_at: int,
    vault_contradictions: Sequence[VaultContradiction] = (),
) -> str:
    """``01-Dashboards/OPERATIONS-DASHBOARD.md`` -- operational rollup:
    counts by status, plus any open contradictions."""
    generated_at_iso = _iso(generated_at)
    counts: dict[str, int] = {}
    for fact in facts:
        counts[fact.status.value] = counts.get(fact.status.value, 0) + 1

    doc = [
        "# Operations Dashboard",
        "",
        f"_Generated by the Titan documentation worker at {generated_at_iso}._",
        "",
        STATUS_LEGEND,
        "",
        "## Status counts",
        "",
    ]
    if counts:
        doc.append("| Status | Count |")
        doc.append("| --- | --- |")
        for status, count in sorted(counts.items()):
            doc.append(f"| {status} | {count} |")
    else:
        doc.append("_No evidence collected this run._")

    doc += ["", "## Open contradictions", ""]
    if contradictions:
        for item in contradictions:
            doc.append(f"- **{item.category}/{item.label}**: {item.description}")
    else:
        doc.append("_None detected this run._")

    if vault_contradictions:
        doc += ["", "## Unresolved contradictions recorded in the vault", ""]
        doc.append(vault_contradictions_section(vault_contradictions))

    return _finalize("\n".join(doc), facts, generated_at_iso)


def render_verification_matrix(
    facts: Sequence[EvidenceFact], *, generated_at: int
) -> str:
    """``09-Evidence/FLEET-VERIFICATION-MATRIX.md`` -- the full evidence
    table, one row per observed fact (not collapsed per subject), so every
    individual collector observation remains traceable."""
    generated_at_iso = _iso(generated_at)
    doc = [
        "# Fleet Verification Matrix",
        "",
        f"_Generated by the Titan documentation worker at {generated_at_iso}._",
        "",
        STATUS_LEGEND,
        "",
        _status_table(facts) if facts else "_No evidence collected this run._",
    ]
    return _finalize("\n".join(doc), facts, generated_at_iso)


def render_daily_evidence(snapshot: EvidenceSnapshot, *, generated_at: int) -> str:
    """``09-Evidence/TITAN-DAILY-EVIDENCE.md`` -- the raw daily evidence
    record, including any collector errors (redacted)."""
    generated_at_iso = _iso(generated_at)
    doc = [
        "# Titan Daily Evidence",
        "",
        f"_Run `{snapshot.run_id}`, generated at {generated_at_iso}._",
        "",
        STATUS_LEGEND,
        "",
        "## Facts",
        "",
        _status_table(snapshot.facts) if snapshot.facts else "_No evidence collected this run._",
        "",
        "## Collector errors",
        "",
    ]
    if snapshot.collector_errors:
        doc += [f"- {error}" for error in snapshot.collector_errors]
    else:
        doc.append("_None._")
    return _finalize("\n".join(doc), snapshot.facts, generated_at_iso)


def render_daily_city_report(
    snapshot: EvidenceSnapshot,
    *,
    generated_at: int,
    prose: Optional[str],
    date_str: str,
) -> str:
    """``01-Daily/YYYY-MM-DD-TITAN-CITY-REPORT.md`` -- the daily
    consolidated narrative report. ``prose`` is optional model-generated
    narrative text (already sanitized); when ``None`` (the deterministic
    fallback path), the report is structured-evidence-only."""
    generated_at_iso = _iso(generated_at)
    doc = [
        f"# Titan Daily Report — {date_str}",
        "",
        f"_Run `{snapshot.run_id}`, generated at {generated_at_iso}._",
        "",
        STATUS_LEGEND,
        "",
        "## Summary",
        "",
    ]
    if prose:
        doc.append(prose)
    else:
        doc.append(
            "_Prose generation was skipped this run (local model unavailable); "
            "the structured evidence below is unaffected._"
        )
    doc += [
        "",
        "## Evidence",
        "",
        _status_table(snapshot.facts) if snapshot.facts else "_No evidence collected this run._",
    ]
    return _finalize("\n".join(doc), snapshot.facts, generated_at_iso)


def render_incident_draft(
    contradiction: Contradiction, *, generated_at: int, run_id: str
) -> str:
    """``00-Inbox/incidents/*.md`` -- a conservative incident draft for a
    meaningful failure or contradiction. Always drafted for human review;
    this worker never files, escalates, or resolves an incident on its
    own."""
    generated_at_iso = _iso(generated_at)
    doc = [
        f"# Incident draft: {contradiction.category}/{contradiction.label}",
        "",
        "**Status: Draft — requires human review.** This document was generated "
        "automatically and has not been triaged.",
        "",
        f"_Run `{run_id}`, generated at {generated_at_iso}._",
        "",
        "## Description",
        "",
        contradiction.description,
        "",
        "## Sources",
        "",
    ]
    doc += [f"- `{source}`" for source in contradiction.sources] or ["_None recorded._"]
    return redact_text("\n".join(doc).rstrip() + "\n")


def vault_contradictions_section(items: Sequence[VaultContradiction]) -> str:
    if not items:
        return "_No unresolved contradictions recorded in the vault._"
    return "\n".join(f"- [[{item.title}]] (`{item.vault_path}`)" for item in items)
