"""The single choke point for every subprocess this worker runs.

Governance requirement: "no arbitrary shell generated by an LLM; subprocess
commands hard-coded and argument-separated." Every ``git``, ``gh``, and
``systemctl`` invocation in this package goes through :func:`run_argv`
rather than calling :mod:`subprocess` directly, so there is exactly one
place that enforces: argv is a real sequence (never a single shell string),
``shell`` is never enabled, every call has a bounded timeout, and the
executable name is drawn from a closed allowlist. No function in this
package ever builds a command line by interpolating model output, vault
content, or any other untrusted text into an argv element that could change
which flags are passed -- untrusted text only ever appears as an inert
argument value (e.g. a commit message string), never concatenated into the
command itself.
"""

from __future__ import annotations

import subprocess
from pathlib import Path
from typing import Mapping, Optional, Sequence

ALLOWED_EXECUTABLES = frozenset({"git", "gh", "systemctl"})


class SubprocessGuardError(RuntimeError):
    """A caller tried to run something outside the allowed shape."""


def run_argv(
    argv: Sequence[str],
    *,
    cwd: Optional[Path] = None,
    timeout: float,
    env: Optional[Mapping[str, str]] = None,
) -> subprocess.CompletedProcess:
    """Run ``argv`` and return the completed process. Never uses a shell.

    Raises :class:`SubprocessGuardError` before ever invoking the OS if
    ``argv`` is not a hard-coded, argument-separated command against an
    allowed executable. Raises ``subprocess.TimeoutExpired`` if the process
    does not finish within ``timeout`` seconds -- callers must always pass
    a bounded timeout; there is no default.
    """
    if isinstance(argv, (str, bytes)):
        raise SubprocessGuardError(
            "argv must be a sequence of arguments, not a single string "
            "(refusing to risk shell-style interpretation)"
        )
    argv = tuple(argv)
    if not argv:
        raise SubprocessGuardError("argv must not be empty")
    if argv[0] not in ALLOWED_EXECUTABLES:
        raise SubprocessGuardError(
            f"executable {argv[0]!r} is not in the allowed set {sorted(ALLOWED_EXECUTABLES)}"
        )
    if not all(isinstance(part, str) for part in argv):
        raise SubprocessGuardError("every argv element must be a string")
    if timeout <= 0:
        raise SubprocessGuardError("timeout must be positive")

    return subprocess.run(
        list(argv),
        cwd=str(cwd) if cwd is not None else None,
        capture_output=True,
        text=True,
        timeout=timeout,
        env=dict(env) if env is not None else None,
        shell=False,
    )
