"""Source provenance for every generated section.

Every Markdown file this worker writes carries a provenance footer
(collector name, source kind, status vocabulary reminder, and timestamp)
generated here so a reader can trace any claim back to the collector that
produced it. :func:`render_source_provenance_update` additionally maintains
an auto-managed block inside the vault's ``SOURCE-PROVENANCE.md`` without
touching anything a human wrote outside that block.
"""

from __future__ import annotations

from typing import Sequence

from pydantic import BaseModel, ConfigDict, Field

from hermes_docs_worker.evidence import EvidenceFact

AUTO_BLOCK_BEGIN = "<!-- BEGIN TITAN-DOCS-WORKER AUTOMATION (do not hand-edit this block) -->"
AUTO_BLOCK_END = "<!-- END TITAN-DOCS-WORKER AUTOMATION -->"


class ProvenanceEntry(BaseModel):
    """One source cited in a generated document."""

    model_config = ConfigDict(frozen=True, extra="forbid")

    source: str = Field(..., min_length=1, max_length=128)
    category: str = Field(..., min_length=1, max_length=64)
    fact_count: int = Field(..., ge=0)
    collected_at: int = Field(..., ge=0)


def provenance_entries_from_facts(facts: Sequence[EvidenceFact]) -> tuple[ProvenanceEntry, ...]:
    by_source: dict[tuple[str, str], dict] = {}
    for fact in facts:
        key = (fact.source, fact.category)
        entry = by_source.setdefault(
            key, {"count": 0, "collected_at": fact.collected_at}
        )
        entry["count"] += 1
        entry["collected_at"] = max(entry["collected_at"], fact.collected_at)
    return tuple(
        ProvenanceEntry(
            source=source, category=category, fact_count=data["count"],
            collected_at=data["collected_at"],
        )
        for (source, category), data in sorted(by_source.items())
    )


def render_provenance_footer(entries: Sequence[ProvenanceEntry], *, generated_at_iso: str) -> str:
    lines = [
        "",
        "---",
        "",
        "**Provenance.** Generated by the Titan documentation worker "
        f"at {generated_at_iso}. Status vocabulary: Implemented, Configured, Verified, "
        "Deployed, Unknown, Degraded, Blocked, Planned — see "
        "`docs/hermes-docs-worker/architecture.md`. Sources for this document:",
        "",
    ]
    if not entries:
        lines.append("- (no collector evidence contributed to this document)")
    for entry in entries:
        lines.append(
            f"- `{entry.source}` ({entry.category}): {entry.fact_count} fact(s) as of "
            f"{entry.collected_at}"
        )
    lines.append("")
    return "\n".join(lines)


def render_source_provenance_update(
    previous_content: str,
    entries: Sequence[ProvenanceEntry],
    *,
    generated_at_iso: str,
    run_id: str,
) -> str:
    """Upsert the auto-managed block inside ``SOURCE-PROVENANCE.md``.

    Content outside :data:`AUTO_BLOCK_BEGIN`/:data:`AUTO_BLOCK_END` is
    preserved byte-for-byte -- this function only ever replaces the text
    strictly between those two markers, appending them (with an empty
    block) if they are not already present so a first run on a vault that
    predates this worker doesn't clobber existing human-authored content.
    """
    block_lines = [AUTO_BLOCK_BEGIN, "", f"_Last updated by run `{run_id}` at {generated_at_iso}._", ""]
    if not entries:
        block_lines.append("No automated evidence sources recorded in the most recent run.")
    else:
        block_lines.append("| Source | Category | Facts | Last collected (epoch) |")
        block_lines.append("| --- | --- | --- | --- |")
        for entry in entries:
            block_lines.append(
                f"| `{entry.source}` | {entry.category} | {entry.fact_count} | {entry.collected_at} |"
            )
    block_lines.append("")
    block = "\n".join(block_lines) + AUTO_BLOCK_END

    if AUTO_BLOCK_BEGIN in previous_content and AUTO_BLOCK_END in previous_content:
        before, _, remainder = previous_content.partition(AUTO_BLOCK_BEGIN)
        _, _, after = remainder.partition(AUTO_BLOCK_END)
        return before + block + after

    separator = "\n\n" if previous_content and not previous_content.endswith("\n\n") else ""
    header = "" if previous_content else "# Source Provenance\n\n"
    return f"{previous_content}{separator}{header}{block}\n"
