"""Specialized Agent Roles domain package."""

from .models import (
    AgentRole,
    Assignment,
    AssignmentHandoff,
    AssignmentOutcome,
    AssignmentResult,
    AssignmentStatus,
    BuiltinRole,
    HandoffReason,
    RoleCapability,
    RolePolicy,
    builtin_agent_roles,
    new_assignment_id,
    new_handoff_id,
    new_result_id,
    new_role_id,
)

from .store import (
    AgentRoleProjectState,
    AgentRoleStore,
    AgentRoleStoreError,
    AssignmentVersionError,
    DuplicateRecordError,
    InvalidProjectIdError,
    JournalCorruptionError,
    JournalEventType,
    JournalRecord,
)

from .dispatcher import (
    BacklogItemNotEligibleError,
    BacklogItemNotFoundError,
    DependencyNotSatisfiedError,
    DispatchPersistenceError,
    DispatchReport,
    DispatchResult,
    DispatchResultStatus,
    DispatcherError,
    GovernedDispatcher,
    MatchingRoleNotFoundError,
)

from .service import (
    AgentRoleService,
    AgentRoleServiceError,
    AssignmentAgentMismatchError,
    AssignmentNotFoundError,
    BuiltinRoleConflictError,
    InvalidAssignmentError,
    InvalidAssignmentTransitionError,
    InvalidRoleRegistrationError,
    RoleAlreadyRegisteredError,
    RoleNotFoundError,
)

from hermes_cli.agent_roles.launch import (
    CURRENT_LAUNCH_SCHEMA_VERSION,
    SUPPORTED_LAUNCH_SCHEMA_VERSIONS,
    LaunchContract,
    LaunchContractStatus,
    LaunchEnvironment,
    LaunchPolicy,
    LaunchWorkspace,
    LaunchWorkspaceMode,
)

from hermes_cli.agent_roles.launch_builder import (
    LaunchContractBuildError,
    LaunchContractBuilder,
)

from hermes_cli.agent_roles.launch_validation import (
    LaunchContractValidator,
    LaunchValidationCode,
    LaunchValidationIssue,
    LaunchValidationResult,
    LaunchValidationSeverity,
    RuntimeCompatibility,
)

from hermes_cli.agent_roles.launch_visibility import (
    CONTRACT_EVENT_TYPE,
    VALIDATION_EVENT_TYPE,
    LaunchVisibilityAdapter,
    LaunchVisibilityRecord,
    LaunchVisibilityService,
)

__all__ = [
    "AgentRole",
    "Assignment",
    "AssignmentHandoff",
    "AssignmentOutcome",
    "AssignmentResult",
    "AssignmentStatus",
    "BuiltinRole",
    "HandoffReason",
    "RoleCapability",
    "RolePolicy",
    "builtin_agent_roles",
    "new_assignment_id",
    "new_handoff_id",
    "new_result_id",
    "new_role_id",
    "AgentRoleProjectState",
    "AgentRoleStore",
    "AgentRoleStoreError",
    "AssignmentVersionError",
    "DuplicateRecordError",
    "InvalidProjectIdError",
    "JournalCorruptionError",
    "JournalEventType",
    "JournalRecord",
    "BacklogItemNotEligibleError",
    "BacklogItemNotFoundError",
    "DependencyNotSatisfiedError",
    "DispatchPersistenceError",
    "DispatchReport",
    "DispatchResult",
    "DispatchResultStatus",
    "DispatcherError",
    "GovernedDispatcher",
    "MatchingRoleNotFoundError",
    "AgentRoleService",
    "AgentRoleServiceError",
    "BuiltinRoleConflictError",
    "InvalidRoleRegistrationError",
    "RoleAlreadyRegisteredError",
    "RoleNotFoundError",
    "AssignmentAgentMismatchError",
    "AssignmentNotFoundError",
    "InvalidAssignmentError",
    "InvalidAssignmentTransitionError",
    "CURRENT_LAUNCH_SCHEMA_VERSION",
    "SUPPORTED_LAUNCH_SCHEMA_VERSIONS",
    "LaunchContract",
    "LaunchContractStatus",
    "LaunchEnvironment",
    "LaunchPolicy",
    "LaunchWorkspace",
    "LaunchWorkspaceMode",
    "LaunchContractBuildError",
    "LaunchContractBuilder",
    "LaunchContractValidator",
    "LaunchValidationCode",
    "LaunchValidationIssue",
    "LaunchValidationResult",
    "LaunchValidationSeverity",
    "RuntimeCompatibility",
    "CONTRACT_EVENT_TYPE",
    "VALIDATION_EVENT_TYPE",
    "LaunchVisibilityAdapter",
    "LaunchVisibilityRecord",
    "LaunchVisibilityService",
]
