"""Specialized Agent Roles domain package."""

from .models import (
    AgentRole,
    Assignment,
    AssignmentHandoff,
    AssignmentOutcome,
    AssignmentResult,
    AssignmentStatus,
    BuiltinRole,
    HandoffReason,
    RoleCapability,
    RolePolicy,
    builtin_agent_roles,
    new_assignment_id,
    new_handoff_id,
    new_result_id,
    new_role_id,
)

from .store import (
    AgentRoleProjectState,
    AgentRoleStore,
    AgentRoleStoreError,
    AssignmentVersionError,
    DuplicateRecordError,
    InvalidProjectIdError,
    JournalCorruptionError,
    JournalEventType,
    JournalRecord,
)

from .service import (
    AgentRoleService,
    AgentRoleServiceError,
    BuiltinRoleConflictError,
    InvalidRoleRegistrationError,
    RoleAlreadyRegisteredError,
    RoleNotFoundError,
)

__all__ = [
    "AgentRole",
    "Assignment",
    "AssignmentHandoff",
    "AssignmentOutcome",
    "AssignmentResult",
    "AssignmentStatus",
    "BuiltinRole",
    "HandoffReason",
    "RoleCapability",
    "RolePolicy",
    "builtin_agent_roles",
    "new_assignment_id",
    "new_handoff_id",
    "new_result_id",
    "new_role_id",
    "AgentRoleProjectState",
    "AgentRoleStore",
    "AgentRoleStoreError",
    "AssignmentVersionError",
    "DuplicateRecordError",
    "InvalidProjectIdError",
    "JournalCorruptionError",
    "JournalEventType",
    "JournalRecord",
    "AgentRoleService",
    "AgentRoleServiceError",
    "BuiltinRoleConflictError",
    "InvalidRoleRegistrationError",
    "RoleAlreadyRegisteredError",
    "RoleNotFoundError",
]
