"""Specialized Agent Roles domain package."""

from .models import (
    AgentRole,
    Assignment,
    AssignmentHandoff,
    AssignmentOutcome,
    AssignmentResult,
    AssignmentStatus,
    BuiltinRole,
    HandoffReason,
    RoleCapability,
    RolePolicy,
    builtin_agent_roles,
    new_assignment_id,
    new_handoff_id,
    new_result_id,
    new_role_id,
)

from .store import (
    AgentRoleProjectState,
    AgentRoleStore,
    AgentRoleStoreError,
    AssignmentVersionError,
    DuplicateRecordError,
    InvalidProjectIdError,
    JournalCorruptionError,
    JournalEventType,
    JournalRecord,
)

from .dispatcher import (
    BacklogItemNotEligibleError,
    BacklogItemNotFoundError,
    DependencyNotSatisfiedError,
    DispatchPersistenceError,
    DispatchReport,
    DispatchResult,
    DispatchResultStatus,
    DispatcherError,
    GovernedDispatcher,
    MatchingRoleNotFoundError,
)

from .service import (
    AgentRoleService,
    AgentRoleServiceError,
    AssignmentAgentMismatchError,
    AssignmentNotFoundError,
    BuiltinRoleConflictError,
    InvalidAssignmentError,
    InvalidAssignmentTransitionError,
    InvalidRoleRegistrationError,
    RoleAlreadyRegisteredError,
    RoleNotFoundError,
)

from hermes_cli.agent_roles.launch import (
    CURRENT_LAUNCH_SCHEMA_VERSION,
    SUPPORTED_LAUNCH_SCHEMA_VERSIONS,
    LaunchContract,
    LaunchContractStatus,
    LaunchEnvironment,
    LaunchPolicy,
    LaunchWorkspace,
    LaunchWorkspaceMode,
)

from hermes_cli.agent_roles.launch_builder import (
    LaunchContractBuildError,
    LaunchContractBuilder,
)

from hermes_cli.agent_roles.launch_validation import (
    LaunchContractValidator,
    LaunchValidationCode,
    LaunchValidationIssue,
    LaunchValidationResult,
    LaunchValidationSeverity,
    RuntimeCompatibility,
)

from hermes_cli.agent_roles.launch_visibility import (
    CONTRACT_EVENT_TYPE,
    VALIDATION_EVENT_TYPE,
    LaunchVisibilityAdapter,
    LaunchVisibilityRecord,
    LaunchVisibilityService,
)

from hermes_cli.agent_roles.runtime_handoff import (
    RUNTIME_HANDOFF_SCHEMA_VERSION,
    DeterministicDryRunAdapter,
    RuntimeAdapter,
    RuntimeHandoffMode,
    RuntimeHandoffReceipt,
    RuntimeHandoffRequest,
    RuntimeHandoffService,
    RuntimeHandoffStatus,
)

from hermes_cli.agent_roles.runtime_session import (
    RUNTIME_SESSION_SCHEMA_VERSION,
    RuntimeSession,
    RuntimeSessionEvent,
    RuntimeSessionFactory,
    RuntimeSessionService,
    RuntimeSessionState,
    RuntimeSessionTransition,
)

from hermes_cli.agent_roles.execution_planning import (
    EXECUTION_PLAN_SCHEMA_VERSION,
    ExecutionAction,
    ExecutionPlanStep,
    RoleExecutionPlan,
    RoleExecutionPlanner,
)

from hermes_cli.agent_roles.execution import (
    EXECUTION_RESULT_SCHEMA_VERSION,
    ExecutionEvidence,
    ExecutionOutcome,
    ExecutionResult,
    FailureCategory,
    GovernedExecutionService,
    PolicyDecision,
    RetryDecision,
)

from hermes_cli.agent_roles.execution_visibility import (
    EXECUTION_EVENT_TYPE,
    ExecutionVisibilityAdapter,
    ExecutionVisibilityRecord,
    ExecutionVisibilityService,
)

__all__ = [
    "AgentRole",
    "Assignment",
    "AssignmentHandoff",
    "AssignmentOutcome",
    "AssignmentResult",
    "AssignmentStatus",
    "BuiltinRole",
    "HandoffReason",
    "RoleCapability",
    "RolePolicy",
    "builtin_agent_roles",
    "new_assignment_id",
    "new_handoff_id",
    "new_result_id",
    "new_role_id",
    "AgentRoleProjectState",
    "AgentRoleStore",
    "AgentRoleStoreError",
    "AssignmentVersionError",
    "DuplicateRecordError",
    "InvalidProjectIdError",
    "JournalCorruptionError",
    "JournalEventType",
    "JournalRecord",
    "BacklogItemNotEligibleError",
    "BacklogItemNotFoundError",
    "DependencyNotSatisfiedError",
    "DispatchPersistenceError",
    "DispatchReport",
    "DispatchResult",
    "DispatchResultStatus",
    "DispatcherError",
    "GovernedDispatcher",
    "MatchingRoleNotFoundError",
    "AgentRoleService",
    "AgentRoleServiceError",
    "BuiltinRoleConflictError",
    "InvalidRoleRegistrationError",
    "RoleAlreadyRegisteredError",
    "RoleNotFoundError",
    "AssignmentAgentMismatchError",
    "AssignmentNotFoundError",
    "InvalidAssignmentError",
    "InvalidAssignmentTransitionError",
    "CURRENT_LAUNCH_SCHEMA_VERSION",
    "SUPPORTED_LAUNCH_SCHEMA_VERSIONS",
    "LaunchContract",
    "LaunchContractStatus",
    "LaunchEnvironment",
    "LaunchPolicy",
    "LaunchWorkspace",
    "LaunchWorkspaceMode",
    "LaunchContractBuildError",
    "LaunchContractBuilder",
    "LaunchContractValidator",
    "LaunchValidationCode",
    "LaunchValidationIssue",
    "LaunchValidationResult",
    "LaunchValidationSeverity",
    "RuntimeCompatibility",
    "CONTRACT_EVENT_TYPE",
    "VALIDATION_EVENT_TYPE",
    "LaunchVisibilityAdapter",
    "LaunchVisibilityRecord",
    "LaunchVisibilityService",
    "RUNTIME_HANDOFF_SCHEMA_VERSION",
    "DeterministicDryRunAdapter",
    "RuntimeAdapter",
    "RuntimeHandoffMode",
    "RuntimeHandoffReceipt",
    "RuntimeHandoffRequest",
    "RuntimeHandoffService",
    "RuntimeHandoffStatus",
    "RUNTIME_SESSION_SCHEMA_VERSION",
    "RuntimeSession",
    "RuntimeSessionEvent",
    "RuntimeSessionFactory",
    "RuntimeSessionService",
    "RuntimeSessionState",
    "RuntimeSessionTransition",
    "EXECUTION_PLAN_SCHEMA_VERSION",
    "ExecutionAction",
    "ExecutionPlanStep",
    "RoleExecutionPlan",
    "RoleExecutionPlanner",
    "EXECUTION_RESULT_SCHEMA_VERSION",
    "ExecutionEvidence",
    "ExecutionOutcome",
    "ExecutionResult",
    "FailureCategory",
    "GovernedExecutionService",
    "PolicyDecision",
    "RetryDecision",
    "EXECUTION_EVENT_TYPE",
    "ExecutionVisibilityAdapter",
    "ExecutionVisibilityRecord",
    "ExecutionVisibilityService",
]
