"""Governed, model-neutral AI provider foundation for Sigil."""

from .analysis import (
    ADVISORY_RESPONSIBILITIES,
    AnalysisValidationError,
    GenericAnalysisPayload,
    GovernedAnalysisArtifact,
    GovernedAnalysisRequest,
    GovernedOutputSchema,
    build_analysis_artifact,
    validate_generic_analysis,
)
from .artifact_store import (
    AnalysisArtifactConflictError,
    AnalysisArtifactCorruptionError,
    AnalysisArtifactStoreError,
    DurableAnalysisArtifactStore,
)
from .evidence import InvocationEvidence, build_invocation_evidence
from .finbert import (
    FINBERT_RESPONSIBILITIES,
    FinBERTConfig,
    FinBERTSentimentPayload,
    FinBERTValidationError,
    GovernedSentimentArtifact,
    GovernedSentimentRequest,
    LocalFinBERTProvider,
    SentimentAggregation,
    SentimentLabel,
    SentimentSourceType,
    aggregate_sentiment,
    build_sentiment_artifact,
    validate_finbert_output,
)
from .gemma import (
    GemmaConfigurationError,
    GemmaHealth,
    GemmaTransportError,
    GemmaTransportFailure,
    LocalGemmaConfig,
    LocalGemmaProvider,
)
from .handoff import GovernedModelWorkRequest, GovernedSentimentWorkRequest
from .ledger import (
    AIEvidenceConflictError,
    AIEvidenceCorruptionError,
    AIEvidenceLedgerError,
    AIEvidenceRecordType,
    DurableAIEvidenceLedger,
    GovernedAIEvidenceRecord,
    append_routing_decision,
)
from .models import (
    Capability,
    CostClass,
    ExecutionLocation,
    InputType,
    ModelRegistration,
    PrivacyTier,
    ProviderHealth,
    ProviderIdentity,
    Responsibility,
    TrustTier,
)
from .provider import (
    DeterministicProvider,
    DeterministicProviderMode,
    ProviderFailure,
    ProviderFailureClass,
    ProviderInvocation,
    ProviderResult,
)
from .registry import GovernedModelRegistry, RegistryValidationError
from .routing import (
    CandidateEvaluation,
    GovernedModelRouter,
    RoutingDecision,
    RoutingFailureClass,
    RoutingRequest,
)
from .service import (
    AnalysisFailureClass,
    GovernedAnalysisResponse,
    GovernedAnalysisService,
    GovernedAnalysisStatus,
)

__all__ = [
    "ADVISORY_RESPONSIBILITIES",
    "FINBERT_RESPONSIBILITIES",
    "AIEvidenceConflictError",
    "AIEvidenceCorruptionError",
    "AIEvidenceLedgerError",
    "AIEvidenceRecordType",
    "AnalysisArtifactConflictError",
    "AnalysisArtifactCorruptionError",
    "AnalysisArtifactStoreError",
    "AnalysisFailureClass",
    "AnalysisValidationError",
    "CandidateEvaluation",
    "Capability",
    "CostClass",
    "DeterministicProvider",
    "DeterministicProviderMode",
    "DurableAIEvidenceLedger",
    "DurableAnalysisArtifactStore",
    "ExecutionLocation",
    "FinBERTConfig",
    "FinBERTSentimentPayload",
    "FinBERTValidationError",
    "GemmaConfigurationError",
    "GemmaHealth",
    "GemmaTransportError",
    "GemmaTransportFailure",
    "GenericAnalysisPayload",
    "GovernedAIEvidenceRecord",
    "GovernedAnalysisArtifact",
    "GovernedAnalysisRequest",
    "GovernedAnalysisResponse",
    "GovernedAnalysisService",
    "GovernedAnalysisStatus",
    "GovernedModelRegistry",
    "GovernedModelRouter",
    "GovernedModelWorkRequest",
    "GovernedOutputSchema",
    "GovernedSentimentArtifact",
    "GovernedSentimentRequest",
    "GovernedSentimentWorkRequest",
    "InputType",
    "InvocationEvidence",
    "LocalFinBERTProvider",
    "LocalGemmaConfig",
    "LocalGemmaProvider",
    "ModelRegistration",
    "PrivacyTier",
    "ProviderFailure",
    "ProviderFailureClass",
    "ProviderHealth",
    "ProviderIdentity",
    "ProviderInvocation",
    "ProviderResult",
    "RegistryValidationError",
    "Responsibility",
    "RoutingDecision",
    "RoutingFailureClass",
    "RoutingRequest",
    "SentimentAggregation",
    "SentimentLabel",
    "SentimentSourceType",
    "TrustTier",
    "aggregate_sentiment",
    "append_routing_decision",
    "build_analysis_artifact",
    "build_invocation_evidence",
    "build_sentiment_artifact",
    "validate_finbert_output",
    "validate_generic_analysis",
]
